name: sspe
channels:
  - defaults
  - pytorch
dependencies:
  - python=3.7
  - pytorch
  - torchvision
  - cudatoolkit=10.2
  - jupyter
  - jupyterlab
  - seaborn
  - tensorboard
  - matplotlib
  - pandas
  - pip
  - pip:
    - torch-scatter
    - torch-geometric

